version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install curl
          command: apk add --no-cache curl
      - run:
          name: Build Docker image
          command: docker build --no-cache --build-arg FTP_USERNAME=$FTP_USERNAME --build-arg FTP_PASSWORD=$FTP_PASSWORD --build-arg FTP_HOSTNAME=$FTP_HOSTNAME -t scholzj/qpid-proton-build:travis .
      - deploy:
          name: Trigger docker image build
          command: |
            curl -u ${CIRCLE_TOKEN}: \
              -d build_parameters[CIRCLE_JOB]=build \
              https://circleci.com/api/v1.1/project/github/scholzj/docker-qpid-proton/tree/master
workflows:
  version: 2
  build-workflow:
    jobs:
      - build:
          context: qpid-repos
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build:
          context: qpid-repos
